# Generated by Django 5.2.4 on 2025-08-04 15:25

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_questionsanswers_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Отзывы')),
                ('user_name', models.CharField(max_length=250, verbose_name='Имя заказчика/покупателя')),
                ('star', models.IntegerField(verbose_name='Звезда отзыва')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateField(verbose_name='Дата выхода отзывов')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='partners', verbose_name='Фото партнеров')),
            ],
            options={
                'verbose_name': 'Партнеры',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='application',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='application',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='tel',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='Без имени', max_length=250, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='recovery_types',
            field=models.CharField(choices=[('По приватному ключу', 'By private key'), ('Через файл Keystore + пароль', 'With Keystore file + password'), ('Через резервную копию', 'With backup'), ('С помощью сервиса поддержки', 'With the help of support service')], default=1, max_length=250, verbose_name='Тип восстановления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='surname',
            field=models.CharField(default=1, max_length=250, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='wallet_type',
            field=models.CharField(choices=[('hardware', 'Аппаратный'), ('software', 'Программный'), ('web', 'Онлайн'), ('mobile', 'Мобильный'), ('exchange', 'Биржевой'), ('paper', 'Бумажный')], default='software', max_length=20, verbose_name='Тип кошелька'),
        ),
        migrations.AddField(
            model_name='application',
            name='wallet_volume',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=12, verbose_name='Объем кошелька'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterModelTable(
            name='application',
            table='Application',
        ),
    ]
