# Generated by Django 5.2.3 on 2025-07-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name='Имя заявщика')),
                ('last_name', models.CharField(verbose_name='Фамилия заявщика')),
                ('country', models.CharField(verbose_name='Страна заявщика')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='E-mail заявщика')),
                ('tel', models.IntegerField(verbose_name='Номер заявщика')),
            ],
            options={
                'verbose_name': 'Заявка',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Новости')),
                ('img', models.ImageField(upload_to='news', verbose_name='Картина новости')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Новости',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='partners', verbose_name='Фото партнеров')),
            ],
            options={
                'verbose_name': 'Партнеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionsAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопросы')),
                ('answer', models.TextField(verbose_name='Ответы')),
            ],
            options={
                'verbose_name': 'Вопросы и ответы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Отзывы')),
                ('user_name', models.CharField(max_length=250, verbose_name='Имя заказчика/покупателя')),
                ('star', models.IntegerField(verbose_name='Звезда отзыва')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateField(verbose_name='Дата выхода отзывов')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'ordering': ['id'],
            },
        ),
    ]
